### PR TITLE
Project structure, dependencies, POM changes

### PR DESCRIPTION
**Pull request by ghost**
Notable changes:
- Source and resource files have been moved to follow the [Standard Directory Layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)
- Default Maven goal is now "clean install"
- Source and build target set to 1.8 (Java 8)
- The plugin.yml version will be automatically changed to the correct version based off of the POM version during compilation
- Dependencies added to the POM (ProtocolLib-API and spigot)

### CODE REVIEW

**Comment by sirrus86** [comment]
After applying these changes, including those to the plugin.yml file, the console now reads "Enabling Apocalypse v${project.version}". How is this resolved?

**Comment by ghost** [comment]
Very strange.

The changes made [here](https://github.com/ImagineCraft/Apocalypse/blob/master/pom.xml#L27-L32) should specifically change that and it does on my end.

A fresh compilation shows the following when enabling the plugin as expected:
`[20:11:40 INFO]: [Apocalypse] Loading Apocalypse v0.5.0`

Which version of maven are you using? You can check this with `mvn -v`

**Comment by sirrus86** [comment]
Command prompt doesn't recognize mvn as a command.

I create my plugins in Eclipse, which has a built-in interface for Maven. I should tell you I have zero experience with Maven; after applying your changes I had to change the project's source folders. Something tells me I'm doing something wrong.

**Comment by ghost** [comment]
The source code folder change sound normal. I know eclipse normally uses /src where as the Maven standard is /src/main/java so having to tell eclipse to change it's ways sounds normal.

It's a bit difficult as I haven't used Eclipse for years, and never in combination with Maven.
I'd recommend [installing Maven](https://maven.apache.org/install.html) and using it through the command prompt. The POM changes I made means all you have to do to compile it is open the folder that contains the pom.xml in CMD and run `mvn` (if it's installed locally that is).

**Comment by sirrus86** [comment]
I managed to install Maven, then ran it to compile the plugin (I was previously using Eclipse which seems to ignore Maven). Compiled and ran perfectly! Thanks for the help!

**Comment by ghost** [comment]
Great! Yeah, after I wrote my previous comment it occured to me that you probably just changed the source dir and then 100% used the eclipse compiler thus circumventing all the Maven magic.

Glad you got it working!

**Pull request merged**
